# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Greg Chapple
email: gregchapple1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software developer, technical architect, open source hacker.
  From Dublin, Ireland.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gchp.ie" # the base hostname & protocol for your site
twitter_username: greg_chapple
github_username:  gchp

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

image: /assets/img/banner.jpg

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "gchp"
